### ISSUE TITLE
CDN

### ISSUE THREAD

**Issue by hamdan-Deb** [vednig/opencdn#1]
How can we implement this CDN on our sites and what is it for Ved Nig

**Comment by vednig** [comment]
You can set up your own network of CDN on a single php server.<br> If your site has less than 100k monthly users it will work fine else you'll need to set up a cluster. 
<BR>
See: http://opencdn.hstn.me

**Comment by vednig** [comment]
It provides you simple links and correct content types [A Sample Gif ](http://opencdn.hstn.me/src/teas.php?hash=771571751&value=gif)

**Comment by vednig** [comment]
Similar to Cloudinary but can return anything like .docx or .pdf files stored in your server.

**Comment by hamdan-Deb** [comment]
But it increase the scripts fetching response while a landing page is being opened

**Comment by hamdan-Deb** [comment]
> You can set up your own network of CDN on a single php server.
> If your site has less than 100k monthly users it will work fine else you'll need to set up a cluster.
> 
> 
> See: http://opencdn.hstn.me


Cool

**Comment by hamdan-Deb** [comment]
Wow, I want to learn more about openCdn

I want cdn for https://sairaschoice.com
